/**
 * configapi
 * Config API lets you easily manage configuration at scale.
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.5
 *
 * Do not edit the class manually.
 *
 */

(function(factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/CreateSettingRequest', 'model/CreateSettingResponse', 'model/HttpFormDataParameter', 'model/HttpGetParameter', 'model/HttpOrchestrationHeader', 'model/HttpOrchestrationRequest', 'model/HttpOrchestrationResponse', 'model/HttpOrchestrationTask', 'model/HttpRawBinaryParameter', 'model/HttpRawTextParameter', 'model/HttpWwwFormUrlEncodedParameter', 'model/ListSettingsRequest', 'model/ListSettingsResponse', 'model/SettingValue', 'model/TaskOutputReference', 'model/UpdateSettingRequest', 'model/UpdateSettingResponse', 'api/OrchestratorApi', 'api/SettingsApi'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('./ApiClient'), require('./model/CreateSettingRequest'), require('./model/CreateSettingResponse'), require('./model/HttpFormDataParameter'), require('./model/HttpGetParameter'), require('./model/HttpOrchestrationHeader'), require('./model/HttpOrchestrationRequest'), require('./model/HttpOrchestrationResponse'), require('./model/HttpOrchestrationTask'), require('./model/HttpRawBinaryParameter'), require('./model/HttpRawTextParameter'), require('./model/HttpWwwFormUrlEncodedParameter'), require('./model/ListSettingsRequest'), require('./model/ListSettingsResponse'), require('./model/SettingValue'), require('./model/TaskOutputReference'), require('./model/UpdateSettingRequest'), require('./model/UpdateSettingResponse'), require('./api/OrchestratorApi'), require('./api/SettingsApi'));
  }
}(function(ApiClient, CreateSettingRequest, CreateSettingResponse, HttpFormDataParameter, HttpGetParameter, HttpOrchestrationHeader, HttpOrchestrationRequest, HttpOrchestrationResponse, HttpOrchestrationTask, HttpRawBinaryParameter, HttpRawTextParameter, HttpWwwFormUrlEncodedParameter, ListSettingsRequest, ListSettingsResponse, SettingValue, TaskOutputReference, UpdateSettingRequest, UpdateSettingResponse, OrchestratorApi, SettingsApi) {
  'use strict';

  /**
   * Config_API_lets_you_easily_manage_configuration_at_scale_.<br>
   * The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
   * <p>
   * An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
   * <pre>
   * var CloudmersiveConfigurationApiClient = require('index'); // See note below*.
   * var xxxSvc = new CloudmersiveConfigurationApiClient.XxxApi(); // Allocate the API class we're going to use.
   * var yyyModel = new CloudmersiveConfigurationApiClient.Yyy(); // Construct a model instance.
   * yyyModel.someProperty = 'someValue';
   * ...
   * var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
   * ...
   * </pre>
   * <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
   * and put the application logic within the callback function.</em>
   * </p>
   * <p>
   * A non-AMD browser application (discouraged) might do something like this:
   * <pre>
   * var xxxSvc = new CloudmersiveConfigurationApiClient.XxxApi(); // Allocate the API class we're going to use.
   * var yyy = new CloudmersiveConfigurationApiClient.Yyy(); // Construct a model instance.
   * yyyModel.someProperty = 'someValue';
   * ...
   * var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
   * ...
   * </pre>
   * </p>
   * @module index
   * @version 2.4.3
   */
  var exports = {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient: ApiClient,
    /**
     * The CreateSettingRequest model constructor.
     * @property {module:model/CreateSettingRequest}
     */
    CreateSettingRequest: CreateSettingRequest,
    /**
     * The CreateSettingResponse model constructor.
     * @property {module:model/CreateSettingResponse}
     */
    CreateSettingResponse: CreateSettingResponse,
    /**
     * The HttpFormDataParameter model constructor.
     * @property {module:model/HttpFormDataParameter}
     */
    HttpFormDataParameter: HttpFormDataParameter,
    /**
     * The HttpGetParameter model constructor.
     * @property {module:model/HttpGetParameter}
     */
    HttpGetParameter: HttpGetParameter,
    /**
     * The HttpOrchestrationHeader model constructor.
     * @property {module:model/HttpOrchestrationHeader}
     */
    HttpOrchestrationHeader: HttpOrchestrationHeader,
    /**
     * The HttpOrchestrationRequest model constructor.
     * @property {module:model/HttpOrchestrationRequest}
     */
    HttpOrchestrationRequest: HttpOrchestrationRequest,
    /**
     * The HttpOrchestrationResponse model constructor.
     * @property {module:model/HttpOrchestrationResponse}
     */
    HttpOrchestrationResponse: HttpOrchestrationResponse,
    /**
     * The HttpOrchestrationTask model constructor.
     * @property {module:model/HttpOrchestrationTask}
     */
    HttpOrchestrationTask: HttpOrchestrationTask,
    /**
     * The HttpRawBinaryParameter model constructor.
     * @property {module:model/HttpRawBinaryParameter}
     */
    HttpRawBinaryParameter: HttpRawBinaryParameter,
    /**
     * The HttpRawTextParameter model constructor.
     * @property {module:model/HttpRawTextParameter}
     */
    HttpRawTextParameter: HttpRawTextParameter,
    /**
     * The HttpWwwFormUrlEncodedParameter model constructor.
     * @property {module:model/HttpWwwFormUrlEncodedParameter}
     */
    HttpWwwFormUrlEncodedParameter: HttpWwwFormUrlEncodedParameter,
    /**
     * The ListSettingsRequest model constructor.
     * @property {module:model/ListSettingsRequest}
     */
    ListSettingsRequest: ListSettingsRequest,
    /**
     * The ListSettingsResponse model constructor.
     * @property {module:model/ListSettingsResponse}
     */
    ListSettingsResponse: ListSettingsResponse,
    /**
     * The SettingValue model constructor.
     * @property {module:model/SettingValue}
     */
    SettingValue: SettingValue,
    /**
     * The TaskOutputReference model constructor.
     * @property {module:model/TaskOutputReference}
     */
    TaskOutputReference: TaskOutputReference,
    /**
     * The UpdateSettingRequest model constructor.
     * @property {module:model/UpdateSettingRequest}
     */
    UpdateSettingRequest: UpdateSettingRequest,
    /**
     * The UpdateSettingResponse model constructor.
     * @property {module:model/UpdateSettingResponse}
     */
    UpdateSettingResponse: UpdateSettingResponse,
    /**
     * The OrchestratorApi service constructor.
     * @property {module:api/OrchestratorApi}
     */
    OrchestratorApi: OrchestratorApi,
    /**
     * The SettingsApi service constructor.
     * @property {module:api/SettingsApi}
     */
    SettingsApi: SettingsApi
  };

  return exports;
}));
