/**
 * configapi
 * Config API lets you easily manage configuration at scale.
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.5
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.CloudmersiveConfigurationApiClient);
  }
}(this, function(expect, CloudmersiveConfigurationApiClient) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new CloudmersiveConfigurationApiClient.HttpOrchestrationTask();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('HttpOrchestrationTask', function() {
    it('should create an instance of HttpOrchestrationTask', function() {
      // uncomment below and update the code to test HttpOrchestrationTask
      //var instance = new CloudmersiveConfigurationApiClient.HttpOrchestrationTask();
      //expect(instance).to.be.a(CloudmersiveConfigurationApiClient.HttpOrchestrationTask);
    });

    it('should have the property taskName (base name: "TaskName")', function() {
      // uncomment below and update the code to test the property taskName
      //var instance = new CloudmersiveConfigurationApiClient.HttpOrchestrationTask();
      //expect(instance).to.be();
    });

    it('should have the property httpMethod (base name: "HttpMethod")', function() {
      // uncomment below and update the code to test the property httpMethod
      //var instance = new CloudmersiveConfigurationApiClient.HttpOrchestrationTask();
      //expect(instance).to.be();
    });

    it('should have the property URL (base name: "URL")', function() {
      // uncomment below and update the code to test the property URL
      //var instance = new CloudmersiveConfigurationApiClient.HttpOrchestrationTask();
      //expect(instance).to.be();
    });

    it('should have the property httpHeaders (base name: "HttpHeaders")', function() {
      // uncomment below and update the code to test the property httpHeaders
      //var instance = new CloudmersiveConfigurationApiClient.HttpOrchestrationTask();
      //expect(instance).to.be();
    });

    it('should have the property queryParameters (base name: "QueryParameters")', function() {
      // uncomment below and update the code to test the property queryParameters
      //var instance = new CloudmersiveConfigurationApiClient.HttpOrchestrationTask();
      //expect(instance).to.be();
    });

    it('should have the property formDataParameters (base name: "FormDataParameters")', function() {
      // uncomment below and update the code to test the property formDataParameters
      //var instance = new CloudmersiveConfigurationApiClient.HttpOrchestrationTask();
      //expect(instance).to.be();
    });

    it('should have the property wwwFormUrlEncodedParameters (base name: "WwwFormUrlEncodedParameters")', function() {
      // uncomment below and update the code to test the property wwwFormUrlEncodedParameters
      //var instance = new CloudmersiveConfigurationApiClient.HttpOrchestrationTask();
      //expect(instance).to.be();
    });

    it('should have the property rawTextBody (base name: "RawTextBody")', function() {
      // uncomment below and update the code to test the property rawTextBody
      //var instance = new CloudmersiveConfigurationApiClient.HttpOrchestrationTask();
      //expect(instance).to.be();
    });

    it('should have the property rawBinaryBody (base name: "RawBinaryBody")', function() {
      // uncomment below and update the code to test the property rawBinaryBody
      //var instance = new CloudmersiveConfigurationApiClient.HttpOrchestrationTask();
      //expect(instance).to.be();
    });

  });

}));
