/**
 * configapi
 * Config API lets you easily manage configuration at scale.
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.5
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.CloudmersiveConfigurationApiClient);
  }
}(this, function(expect, CloudmersiveConfigurationApiClient) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new CloudmersiveConfigurationApiClient.SettingValue();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('SettingValue', function() {
    it('should create an instance of SettingValue', function() {
      // uncomment below and update the code to test SettingValue
      //var instance = new CloudmersiveConfigurationApiClient.SettingValue();
      //expect(instance).to.be.a(CloudmersiveConfigurationApiClient.SettingValue);
    });

    it('should have the property configSettingValueID (base name: "ConfigSettingValueID")', function() {
      // uncomment below and update the code to test the property configSettingValueID
      //var instance = new CloudmersiveConfigurationApiClient.SettingValue();
      //expect(instance).to.be();
    });

    it('should have the property configSettingDefinitionID (base name: "ConfigSettingDefinitionID")', function() {
      // uncomment below and update the code to test the property configSettingDefinitionID
      //var instance = new CloudmersiveConfigurationApiClient.SettingValue();
      //expect(instance).to.be();
    });

    it('should have the property configSettingValue (base name: "ConfigSettingValue")', function() {
      // uncomment below and update the code to test the property configSettingValue
      //var instance = new CloudmersiveConfigurationApiClient.SettingValue();
      //expect(instance).to.be();
    });

    it('should have the property configSettingLastModified (base name: "ConfigSettingLastModified")', function() {
      // uncomment below and update the code to test the property configSettingLastModified
      //var instance = new CloudmersiveConfigurationApiClient.SettingValue();
      //expect(instance).to.be();
    });

    it('should have the property configSettingName (base name: "ConfigSettingName")', function() {
      // uncomment below and update the code to test the property configSettingName
      //var instance = new CloudmersiveConfigurationApiClient.SettingValue();
      //expect(instance).to.be();
    });

    it('should have the property configSettingDescription (base name: "ConfigSettingDescription")', function() {
      // uncomment below and update the code to test the property configSettingDescription
      //var instance = new CloudmersiveConfigurationApiClient.SettingValue();
      //expect(instance).to.be();
    });

    it('should have the property configSettingTags (base name: "ConfigSettingTags")', function() {
      // uncomment below and update the code to test the property configSettingTags
      //var instance = new CloudmersiveConfigurationApiClient.SettingValue();
      //expect(instance).to.be();
    });

    it('should have the property configSettingType (base name: "ConfigSettingType")', function() {
      // uncomment below and update the code to test the property configSettingType
      //var instance = new CloudmersiveConfigurationApiClient.SettingValue();
      //expect(instance).to.be();
    });

  });

}));
