/**
 * configapi
 * Config API lets you easily manage configuration at scale.
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.5
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.CloudmersiveConfigurationApiClient);
  }
}(this, function(expect, CloudmersiveConfigurationApiClient) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new CloudmersiveConfigurationApiClient.SettingsApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('SettingsApi', function() {
    describe('settingsCreateSetting', function() {
      it('should call settingsCreateSetting successfully', function(done) {
        //uncomment below and update the code to test settingsCreateSetting
        //instance.settingsCreateSetting(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('settingsListSettings', function() {
      it('should call settingsListSettings successfully', function(done) {
        //uncomment below and update the code to test settingsListSettings
        //instance.settingsListSettings(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('settingsUpdateSetting', function() {
      it('should call settingsUpdateSetting successfully', function(done) {
        //uncomment below and update the code to test settingsUpdateSetting
        //instance.settingsUpdateSetting(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
