/**
 * configapi
 * Config API lets you easily manage configuration at scale.
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.5
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.CloudmersiveConfigurationApiClient) {
      root.CloudmersiveConfigurationApiClient = {};
    }
    root.CloudmersiveConfigurationApiClient.HttpOrchestrationResponse = factory(root.CloudmersiveConfigurationApiClient.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The HttpOrchestrationResponse model module.
   * @module model/HttpOrchestrationResponse
   * @version 2.4.2
   */

  /**
   * Constructs a new <code>HttpOrchestrationResponse</code>.
   * Result of performing an HTTP orchestration
   * @alias module:model/HttpOrchestrationResponse
   * @class
   */
  var exports = function() {
    var _this = this;





  };

  /**
   * Constructs a <code>HttpOrchestrationResponse</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/HttpOrchestrationResponse} obj Optional instance to populate.
   * @return {module:model/HttpOrchestrationResponse} The populated <code>HttpOrchestrationResponse</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('Successful')) {
        obj['Successful'] = ApiClient.convertToType(data['Successful'], 'Boolean');
      }
      if (data.hasOwnProperty('TasksCompleted')) {
        obj['TasksCompleted'] = ApiClient.convertToType(data['TasksCompleted'], 'Number');
      }
      if (data.hasOwnProperty('Output_StringType')) {
        obj['Output_StringType'] = ApiClient.convertToType(data['Output_StringType'], 'String');
      }
      if (data.hasOwnProperty('Output_BinaryType')) {
        obj['Output_BinaryType'] = ApiClient.convertToType(data['Output_BinaryType'], 'Blob');
      }
    }
    return obj;
  }

  /**
   * True if the operation was successful, false otherwise
   * @member {Boolean} Successful
   */
  exports.prototype['Successful'] = undefined;
  /**
   * Count of the number of tasks that were completed
   * @member {Number} TasksCompleted
   */
  exports.prototype['TasksCompleted'] = undefined;
  /**
   * Result output in string format
   * @member {String} Output_StringType
   */
  exports.prototype['Output_StringType'] = undefined;
  /**
   * Result output in binary format
   * @member {Blob} Output_BinaryType
   */
  exports.prototype['Output_BinaryType'] = undefined;



  return exports;
}));


