/**
 * configapi
 * Config API lets you easily manage configuration at scale.
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.5
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/TaskOutputReference'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./TaskOutputReference'));
  } else {
    // Browser globals (root is window)
    if (!root.CloudmersiveConfigurationApiClient) {
      root.CloudmersiveConfigurationApiClient = {};
    }
    root.CloudmersiveConfigurationApiClient.HttpRawTextParameter = factory(root.CloudmersiveConfigurationApiClient.ApiClient, root.CloudmersiveConfigurationApiClient.TaskOutputReference);
  }
}(this, function(ApiClient, TaskOutputReference) {
  'use strict';




  /**
   * The HttpRawTextParameter model module.
   * @module model/HttpRawTextParameter
   * @version 2.4.3
   */

  /**
   * Constructs a new <code>HttpRawTextParameter</code>.
   * Raw text parameter that defines the entire body of the HTTP payload; cannot be used with other parameter types
   * @alias module:model/HttpRawTextParameter
   * @class
   */
  var exports = function() {
    var _this = this;



  };

  /**
   * Constructs a <code>HttpRawTextParameter</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/HttpRawTextParameter} obj Optional instance to populate.
   * @return {module:model/HttpRawTextParameter} The populated <code>HttpRawTextParameter</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('ParameterValue')) {
        obj['ParameterValue'] = ApiClient.convertToType(data['ParameterValue'], 'String');
      }
      if (data.hasOwnProperty('UseOutputFromPreviousTask')) {
        obj['UseOutputFromPreviousTask'] = TaskOutputReference.constructFromObject(data['UseOutputFromPreviousTask']);
      }
    }
    return obj;
  }

  /**
   * Text value of the parameter
   * @member {String} ParameterValue
   */
  exports.prototype['ParameterValue'] = undefined;
  /**
   * Optional; use the output from a previous task as the input to this parameter.  Set to null (default) to ignore.
   * @member {module:model/TaskOutputReference} UseOutputFromPreviousTask
   */
  exports.prototype['UseOutputFromPreviousTask'] = undefined;



  return exports;
}));


