/**
 * configapi
 * Config API lets you easily manage configuration at scale.
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.5
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/HttpOrchestrationTask'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./HttpOrchestrationTask'));
  } else {
    // Browser globals (root is window)
    if (!root.CloudmersiveConfigurationApiClient) {
      root.CloudmersiveConfigurationApiClient = {};
    }
    root.CloudmersiveConfigurationApiClient.HttpOrchestrationRequest = factory(root.CloudmersiveConfigurationApiClient.ApiClient, root.CloudmersiveConfigurationApiClient.HttpOrchestrationTask);
  }
}(this, function(ApiClient, HttpOrchestrationTask) {
  'use strict';




  /**
   * The HttpOrchestrationRequest model module.
   * @module model/HttpOrchestrationRequest
   * @version 2.4.3
   */

  /**
   * Constructs a new <code>HttpOrchestrationRequest</code>.
   * HTTP Orchestration request
   * @alias module:model/HttpOrchestrationRequest
   * @class
   */
  var exports = function() {
    var _this = this;


  };

  /**
   * Constructs a <code>HttpOrchestrationRequest</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/HttpOrchestrationRequest} obj Optional instance to populate.
   * @return {module:model/HttpOrchestrationRequest} The populated <code>HttpOrchestrationRequest</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('HttpTasks')) {
        obj['HttpTasks'] = ApiClient.convertToType(data['HttpTasks'], [HttpOrchestrationTask]);
      }
    }
    return obj;
  }

  /**
   * Tasks to perform, in the order you wish to perform them
   * @member {Array.<module:model/HttpOrchestrationTask>} HttpTasks
   */
  exports.prototype['HttpTasks'] = undefined;



  return exports;
}));


