/**
 * configapi
 * Config API lets you easily manage configuration at scale.
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.5
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.CloudmersiveConfigurationApiClient) {
      root.CloudmersiveConfigurationApiClient = {};
    }
    root.CloudmersiveConfigurationApiClient.TaskOutputReference = factory(root.CloudmersiveConfigurationApiClient.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The TaskOutputReference model module.
   * @module model/TaskOutputReference
   * @version 2.4.3
   */

  /**
   * Constructs a new <code>TaskOutputReference</code>.
   * Re-use the output from a previously-completed task
   * @alias module:model/TaskOutputReference
   * @class
   */
  var exports = function() {
    var _this = this;



  };

  /**
   * Constructs a <code>TaskOutputReference</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/TaskOutputReference} obj Optional instance to populate.
   * @return {module:model/TaskOutputReference} The populated <code>TaskOutputReference</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('TaskName')) {
        obj['TaskName'] = ApiClient.convertToType(data['TaskName'], 'String');
      }
      if (data.hasOwnProperty('TargetType')) {
        obj['TargetType'] = ApiClient.convertToType(data['TargetType'], 'String');
      }
    }
    return obj;
  }

  /**
   * Name of the task to use the output from
   * @member {String} TaskName
   */
  exports.prototype['TaskName'] = undefined;
  /**
   * Type to convert the output from the referenced task to; possible values are string, binary
   * @member {String} TargetType
   */
  exports.prototype['TargetType'] = undefined;



  return exports;
}));


