/**
 * configapi
 * Config API lets you easily manage configuration at scale.
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.5
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/SettingValue'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./SettingValue'));
  } else {
    // Browser globals (root is window)
    if (!root.CloudmersiveConfigurationApiClient) {
      root.CloudmersiveConfigurationApiClient = {};
    }
    root.CloudmersiveConfigurationApiClient.UpdateSettingRequest = factory(root.CloudmersiveConfigurationApiClient.ApiClient, root.CloudmersiveConfigurationApiClient.SettingValue);
  }
}(this, function(ApiClient, SettingValue) {
  'use strict';




  /**
   * The UpdateSettingRequest model module.
   * @module model/UpdateSettingRequest
   * @version 2.4.3
   */

  /**
   * Constructs a new <code>UpdateSettingRequest</code>.
   * Request to update a setting
   * @alias module:model/UpdateSettingRequest
   * @class
   */
  var exports = function() {
    var _this = this;




  };

  /**
   * Constructs a <code>UpdateSettingRequest</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/UpdateSettingRequest} obj Optional instance to populate.
   * @return {module:model/UpdateSettingRequest} The populated <code>UpdateSettingRequest</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('BucketID')) {
        obj['BucketID'] = ApiClient.convertToType(data['BucketID'], 'String');
      }
      if (data.hasOwnProperty('BucketSecretKey')) {
        obj['BucketSecretKey'] = ApiClient.convertToType(data['BucketSecretKey'], 'String');
      }
      if (data.hasOwnProperty('SettingToUpdate')) {
        obj['SettingToUpdate'] = SettingValue.constructFromObject(data['SettingToUpdate']);
      }
    }
    return obj;
  }

  /**
   * @member {String} BucketID
   */
  exports.prototype['BucketID'] = undefined;
  /**
   * @member {String} BucketSecretKey
   */
  exports.prototype['BucketSecretKey'] = undefined;
  /**
   * @member {module:model/SettingValue} SettingToUpdate
   */
  exports.prototype['SettingToUpdate'] = undefined;



  return exports;
}));


