/**
 * configapi
 * Config API lets you easily manage configuration at scale.
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.5
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/HttpOrchestrationRequest', 'model/HttpOrchestrationResponse'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('../model/HttpOrchestrationRequest'), require('../model/HttpOrchestrationResponse'));
  } else {
    // Browser globals (root is window)
    if (!root.CloudmersiveConfigurationApiClient) {
      root.CloudmersiveConfigurationApiClient = {};
    }
    root.CloudmersiveConfigurationApiClient.OrchestratorApi = factory(root.CloudmersiveConfigurationApiClient.ApiClient, root.CloudmersiveConfigurationApiClient.HttpOrchestrationRequest, root.CloudmersiveConfigurationApiClient.HttpOrchestrationResponse);
  }
}(this, function(ApiClient, HttpOrchestrationRequest, HttpOrchestrationResponse) {
  'use strict';

  /**
   * Orchestrator service.
   * @module api/OrchestratorApi
   * @version 2.4.3
   */

  /**
   * Constructs a new OrchestratorApi. 
   * @alias module:api/OrchestratorApi
   * @class
   * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
   * default to {@link module:ApiClient#instance} if unspecified.
   */
  var exports = function(apiClient) {
    this.apiClient = apiClient || ApiClient.instance;


    /**
     * Callback function to receive the result of the orchestratorHttpSimple operation.
     * @callback module:api/OrchestratorApi~orchestratorHttpSimpleCallback
     * @param {String} error Error message, if any.
     * @param {module:model/HttpOrchestrationResponse} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Orchestrate multiple HTTP API calls with a single API call in the order specified.  Call other Cloudmersive APIs or third party APIs.  For Cloudmersive APIs, the API Key will automatically propogate to the child calls without needing to be set explicitly.  Name each task and reference the output of a previous task in the inputs to a given task.
     * @param {module:model/HttpOrchestrationRequest} request 
     * @param {module:api/OrchestratorApi~orchestratorHttpSimpleCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/HttpOrchestrationResponse}
     */
    this.orchestratorHttpSimple = function(request, callback) {
      var postBody = request;

      // verify the required parameter 'request' is set
      if (request === undefined || request === null) {
        throw new Error("Missing the required parameter 'request' when calling orchestratorHttpSimple");
      }


      var pathParams = {
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['Apikey'];
      var contentTypes = ['application/json', 'text/json', 'application/xml', 'text/xml', 'application/x-www-form-urlencoded'];
      var accepts = ['application/json', 'text/json', 'application/xml', 'text/xml'];
      var returnType = HttpOrchestrationResponse;

      return this.apiClient.callApi(
        '/config/orchestrator/http/simple', 'POST',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
  };

  return exports;
}));
